name: Deploy Shiny App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      - name: Install R packages
        run: |
          Rscript -e 'install.packages(c("shiny", "rsconnect"), repos="https://cran.rstudio.com")'

      - name: Deploy to shinyapps.io
        env:
          SHINYAPPS_TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}
          SHINYAPPS_SECRET: ${{ secrets.SHINYAPPS_SECRET }}
        run: |
          Rscript -e '
            library(rsconnect);
            rsconnect::setAccountInfo(name="raquellima",
                                      token=Sys.getenv("SHINYAPPS_TOKEN"),
                                      secret=Sys.getenv("SHINYAPPS_SECRET"));
            rsconnect::deployApp(appDir = "UI-EM3-main/Tool", appName = "test-ui-em3", forceUpdate = TRUE)
          '
